production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_secret: placeholder
  some_password: placeholder

development:
  secret_key_base: a_secure_dev_secret_key

test:
  secret_key_base: a_secure_test_secret_key